### ISSUE TITLE
I have found this from the bgfx page and i want to do my congrats to the developer!

### ISSUE THREAD

**Issue by RealAquilus** [volcoma/EtherealEngine#10]
Ok sorry this is not an issues, but i have just found this i want to say my congrats to the developer, this seems amazing!!!! I LOVE THE GUI!!! Keep going my friend, i will follow you!

PS Will this have an internal script editor like the one of Stingray and Visual Scripting in the future?

Can't wait to play around with this in Windows!

**Comment by volcoma** [comment]
Thanks man:). It is still pretty early. But if I get to that stage I will definately consider it.

**Comment by RealAquilus** [comment]
Keep going my friend! i will follow this project!
