### ISSUE TITLE
GUI memory free problem when shutdown

### ISSUE THREAD

**Issue by qiaone** [volcoma/EtherealEngine#13]
![devenv_2017-10-28_20-58-39](https://user-images.githubusercontent.com/5222364/32134599-d12df674-bc22-11e7-8095-79ba9f07fa96.png)

In Visual Studio, debug the application, just close the start page(project manager), Visual Studio will prompt an exception in ImGui::MemFree

**Comment by volcoma** [comment]
Does this happen every time? I will look into it.

**Comment by qiaone** [comment]
Yes, it can be reproduced both on my desktop and laptop. Thanks.

**Comment by volcoma** [comment]
I will fix this on Monday. Thanks for the issue.
