### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by zhouxs1023** [volcoma/EtherealEngine#14]
I use cmake 3.80 do makelist,but turn on error:

CMake Error at 3rdparty/bgfx/cmake/3rdparty/glsl-optimizer.cmake:73 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.

![360-164408199794146](https://user-images.githubusercontent.com/905931/32378066-b0dc04d0-c0e4-11e7-8b8a-56111a02f5af.png)

**Comment by volcoma** [comment]
from the log you showed me it seems like you are missing the source for all of these libs.
Did u udpate the submodules when u cloned the repo? Try following the steps in the building section of the repo description.

**Comment by volcoma** [comment]
Can you tell me if it is still an issue.

**Comment by zhouxs1023** [comment]
Oh, I miss bgfx source, now I have sucessfully cmake source
Thanks you for help me !
