### ISSUE TITLE
EXE run turn on error

### ISSUE THREAD

**Issue by zhouxs1023** [volcoma/EtherealEngine#15]
latest source may  be successfully compiled,but running exe turn on error as blow:

![1651100686106129-0](https://user-images.githubusercontent.com/905931/32406005-3babe082-c1ab-11e7-8dbb-f3d89821f292.png)

but change desktop.width/height from 100 to 0, may run successfully, if this a bug?
![1681031410412093](https://user-images.githubusercontent.com/905931/32406010-41466c2e-c1ab-11e7-8dc1-b0bd06b300f9.png)
![16741207113100142-1](https://user-images.githubusercontent.com/905931/32406012-44f106d6-c1ab-11e7-9bcf-57ee25928bbe.png)

**Comment by volcoma** [comment]
This should not happen.  Tested it on windows 10 / Linux , gcc. clang, mingw and msvs compiled and cant reproduce it on my end. What setup are you using? Are you running the exe in debug/release mode? Any callstacks? Any way to reproduce it?

**Comment by zhouxs1023** [comment]
I use win7 x64 and vs2015 to compile latest source, It might be my computer graphics problem!
