### ISSUE TITLE
is math::qualifier missing

### ISSUE THREAD

**Issue by tigerssj** [volcoma/EtherealEngine#20]
compile errors;
3>g:\lo\bgfx-master\etherealengine\engine\runtime\meta\rendering\../core/math/vector.hpp(8): error C2039: “qualifier”: 不是“math”的成员 (编译源文件 G:\lo\bgfx-master\EtherealEngine\engine\runtime\meta\rendering\reflection_probe.cpp)
3>  G:\lo\bgfx-master\EtherealEngine\engine\core/math/math_includes.h(12): note: 参见“math”的声明 (编译源文件 G:\lo\bgfx-master\EtherealEngine\engine\runtime\meta\rendering\reflection_probe.cpp)
3>g:\lo\bgfx-master\etherealengine\engine\runtime\meta\rendering\../core/math/vector.hpp(8): error C2061: 语法错误: 标识符“qualifier” (编译源文件

source code:
template <typename Archive, typename T, math::qualifier P>
inline void SERIALIZE_FUNCTION_NAME(Archive& ar, math::tvec2<T, P>& obj)
{
	try_serialize(ar, cereal::make_nvp("x", obj.x));
	try_serialize(ar, cereal::make_nvp("y", obj.y));
}

**Comment by volcoma** [comment]
hmm... This should not happen since a lot of things depend on this serialization function. Can you give more specifics on your system/compiler that you are using to compile it?

**Comment by tigerssj** [comment]
Thank you for your prompt reply!

System type: 64-bit Operating System, x64-based processor  Windows10 Enterprise

Compiler: Microsoft  Visual studio community 2015 14.0.25431.01 Update3

Debug x86

Generate the solution by CMake 3.6.1!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by volcoma** [comment]
Well everything works fine here... Can you just for the hell of it try to replace the math namespace with the glm namespace in those serialization functions

**Comment by tigerssj** [comment]
You mean:
[cid:image001.png@01D3913F.856544D0]

Here are the Configure Entities in CMake:
[cid:image002.png@01D3913F.D50729E0][cid:image003.png@01D3913F.D50729E0][cid:image004.png@01D3913F.D50729E0][cid:image005.png@01D3913F.D50729E0][cid:image006.png@01D3913F.D50729E0][cid:image007.png@01D3913F.D50729E0][cid:image008.png@01D3913F.D50729E0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by volcoma** [comment]
cant see those images.

**Comment by volcoma** [comment]
You should not touch the default cmake options as they should be preconfigured. Just configure and generate. Did you update the submodules?

**Comment by tigerssj** [comment]
May be I Used invalid gml version… the version number of glm in my project is 0.9.9

I generate the solution with cmake. I only modified the entities: BGFX_DIR, BIMG_DIR, BX_DIR

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by volcoma** [comment]
Its the same here too. Can you try making a clean clone of the repo in some other folder. then update the submodules like so
```
git clone https://github.com/volcoma/EtherealEngine.git
cd EtherealEngine
git submodule init
git submodule update
```

and try to generate your solution without modifying cmake options and then build it.

**Comment by tigerssj** [comment]
Thank you!  I am going to try it!
I will Relay you later!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by volcoma** [comment]
Did you manage to work it out?

**Comment by tigerssj** [comment]
Yes,  I Updated All Submodule, and compiled again…..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
