### ISSUE TITLE
crash in bgfx 

### ISSUE THREAD

**Issue by tao8888821** [volcoma/EtherealEngine#21]
void memCopy(void* _dst, const void* _src, size_t _numBytes)
	{
#if BX_CRT_NONE
		memCopyRef(_dst, _src, _numBytes);
#else
		::memcpy(_dst, _src, _numBytes);
#endif // BX_CRT_NONE
	}

**Comment by volcoma** [comment]
I've updated bgfx to master. Can you still repreoduce this. Can you give me a more detailed repo? Platform, renderer, callstack, some use case, because crash in memcpy tells me nothing.
