### ISSUE TITLE
error when I run on windows 8

### ISSUE THREAD

**Issue by yoyo-sincerely** [volcoma/EtherealEngine#22]
hello.
I run command
```
cmake -G "Visual Studio 15 2017 Win64" ..
```
on win 8
then when I run **editor** project, I get an error:
```
Exception thrown: read access violation.
this->m_factory-> was 0xFFFFFFFFFFFFFF1F.
```
It is happen in file dxgi.cpp line 409.
```
hr = m_factory->CheckFeatureSupport(DXGI_FEATURE_PRESENT_ALLOW_TEARING, &allowTearing, sizeof(allowTearing) );
```
How can I fix the problem?

the stack is :
![](https://github.com/yoyo-sincerely/MyPic/blob/master/Bug/Bug.png?raw=true)

**Comment by volcoma** [comment]
Hey is there something logged in the console or in the log file in the executable folder? Seems like it couldn't init the dxgi factory for some reason. What's your graphics hardware?
