### ISSUE TITLE
Engine filed to compile

### ISSUE THREAD

**Issue by dragonCASTjosh** [volcoma/EtherealEngine#3]
Under the lastest commits the engine fails to compile, from what i can gather its because all the files in "runtime/rendering/debug" are missing. Im not sure if these files were refactored but there are still some references to it in the engine

**Comment by volcoma** [comment]
hm just a sec and i will fix it. mabe some files failed to sync

**Comment by volcoma** [comment]
this should be resolved now. it was a gitignore issue due to the debug name of the folder

**Comment by dragonCASTjosh** [comment]
Looks to be compiling fine now, if it breaks fails ill reopen.
