### ISSUE TITLE
Scripting support (lua)

### ISSUE THREAD

**Issue by amerkoleci** [volcoma/EtherealEngine#4]
Any plan to add scripting support using Lua or something else?

**Comment by volcoma** [comment]
Well i've been thinking about it. If i do decide to, it will be either C# or lua

**Comment by dragonCASTjosh** [comment]
i vote C#

**Comment by ArnCarveris** [comment]
C# is great buts is heavy, better use lua with jit, 
but still, those is way better than any game scripting(from designer perspective).
https://github.com/CRYTEK-CRYENGINE/CRYENGINE/tree/release/Code/CryEngine/CrySchematyc
https://github.com/CRYTEK-CRYENGINE/CRYENGINE/tree/release/Code/CryEngine/CryAction/FlowSystem

**Comment by dragonCASTjosh** [comment]
C# dont have to be heavy. Its possible to have your core engine compile into a C++ DLL and load that directly into C#, although not sure if that's windows only. Also .net core is fairly lightweight. My issues with LUA is every engine i have seen use it has try to remove and looked for alternatives. Also i do like visual script systems they are very good for prototyping.

**Comment by christianclavet** [comment]
These could be added as components. If anything is implemented, would be nice to have the option use it or not, perhaps by having options somewhere to disable/enable them from the build.

**Comment by ArnCarveris** [comment]
Components are not enough, there should be subsystem.

**Comment by ArnCarveris** [comment]
Found great lib for [Lua](https://github.com/ThePhD/sol2)

**Comment by volcoma** [comment]
I played around with it last week haha. Its pretty easy to get into.

**Comment by ArnCarveris** [comment]
Found simple implementation of [visual scripting module in godot engine](https://github.com/godotengine/godot/tree/master/modules/visual_script)

**Comment by ArnCarveris** [comment]
Implemented simple [data oriented graph lib on c](https://gitlab.com/arn-carver/cxx/legacy/utils/data/graph/graph) not tested yet, this will be used by graph editor.

**Comment by ArnCarveris** [comment]
Found good [Modular Lexical Analyser Generator](https://github.com/BenHanson/lexertl)

**Comment by ArnCarveris** [comment]
@volcoma Finally [scripting example](https://github.com/rttrorg/rttr/issues/28) for `rttr`

**Comment by barefists** [comment]
A vote for C# here as well.

Like what @dragonCASTjosh said, the engine could be compiled into a library for use within C# instead of the other way around.

The major advantage of this is access to the entire dotnet ecosystem: Networking via [LiteNetLib](https://github.com/RevenantX/LiteNetLib), Sound via [NAudio](https://github.com/naudio/NAudio), etc.
