### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by huperniketes** [volcoma/EtherealEngine#5]
What license are you granting others to use EtherealEngine?

Under US laws, you're automatically granted copyright for your work from the moment you created it. Hence, it isn't in the public domain and anyone seeking to incorporate your work, or derive other work from yours, must do so with your express permission.

I'm sorry for being a killjoy here, as you're probably more interested in continuing to work on cool stuff, but those are the ground rules for the creative arts; which, as a fellow creative, I'm actually glad and grateful they did it this way. A lot of other stuff, not so much.

**Comment by volcoma** [comment]
I am sorry that I forgot to set that. I updated the repo and added a LICENCE.md file

**Comment by huperniketes** [comment]
Thanks!
