### ISSUE TITLE
Compiler turn on Error	C1083 error.h

### ISSUE THREAD

**Issue by zhouxs1023** [volcoma/EtherealEngine#9]
I use win7+ vs2015 compiler EtherealEngine to turn on "	Cannot open include file: 'boost/preprocessor/debug/error.hpp': No such file or directory"

![error](https://user-images.githubusercontent.com/905931/29488641-a18b4d1c-8541-11e7-9fa6-cf99115dfc28.png)
pls help me how to deal with these errors? Tks

**Comment by volcoma** [comment]
Lol it seems an error of my end. I guess due to the the .gitignore file the whole debug dir didn't get commited. Will fix it asap

**Comment by volcoma** [comment]
I have fixed it in the latest commit. :). If there are more issues please don't hesitate to write them.

**Comment by volcoma** [comment]
Can you tell me if you were able to compile so that I can close this.

**Comment by zhouxs1023** [comment]
I get latest source to compile, but turn on error C1083 in X86/X32.h as  below:




![error](https://user-images.githubusercontent.com/905931/29491446-ea1f5742-858e-11e7-88cf-d1769c64bbf2.png)

**Comment by volcoma** [comment]
Yet another issue with .gitignore. I fixed it and you can try again :) sorry :)

**Comment by zhouxs1023** [comment]
Compile successfully,Thanks for your help, this project is very cool！
